package health.flo.network.bhttp.mappers

// See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses
internal class HttpResponseCodeToMessageMapper {

    @Suppress("kotlin:S1479")
    fun map(code: Int): String = when (code) {
        100 -> "CONTINUE"
        101 -> "SWITCHING PROTOCOLS"
        103 -> "EARLY HINTS"
        200 -> "OK"
        201 -> "CREATED"
        202 -> "ACCEPTED"
        203 -> "NON-AUTHORITATIVE INFORMATION"
        204 -> "NO CONTENT"
        205 -> "RESET CONTENT"
        206 -> "PARTIAL CONTENT"
        300 -> "MULTIPLE CHOICES"
        301 -> "MOVED PERMANENTLY"
        302 -> "FOUND"
        303 -> "SEE OTHER"
        304 -> "NOT MODIFIED"
        307 -> "TEMPORARY REDIRECT"
        308 -> "PERMANENT REDIRECT"
        400 -> "BAD REQUEST"
        401 -> "UNAUTHORIZED"
        402 -> "PAYMENT REDIRECT"
        403 -> "FORBIDDEN"
        404 -> "NOT FOUND"
        405 -> "METHOD NOT ALLOWED"
        406 -> "NOT ACCEPTABLE"
        407 -> "PROXY AUTHENTICATION REQUIRED"
        408 -> "REQUEST TIMEOUT"
        409 -> "CONFLICT"
        410 -> "GONE"
        411 -> "LENGTH REQUIRED"
        412 -> "PRECONDITION FAILED"
        413 -> "PAYLOAD TOO LARGE"
        414 -> "URI TOO LONG"
        415 -> "UNSUPPORTED MEDIA TYPE"
        416 -> "RANGE NOT SATISFIABLE"
        417 -> "EXPECTATION FAILED"
        418 -> "I'M A TEAPOT"
        421 -> "MISDIRECTED REQUEST"
        425 -> "TOO EARLY"
        426 -> "UPGRADE REQUIRED"
        428 -> "PRECONDITION REQUIRED"
        429 -> "TOO MANY REQUESTS"
        431 -> "REQUEST HEADER FIELDS TOO LARGE"
        451 -> "UNAVAILABLE FOE LEGAL REASONS"
        500 -> "INTERNAL SERVER ERROR"
        501 -> "NOT IMPLEMENTED"
        502 -> "BAD GATEWAY"
        503 -> "SERVICE UNAVAILABLE"
        504 -> "GATEWAY TIMEOUT"
        505 -> "HTTP VERSION NOT SUPPORTED"
        506 -> "VARIANT ALSO NEGOTIATES"
        510 -> "NOT EXTENDED"
        511 -> "NETWORK AUTHENTICATION REQUIRED"
        else -> "UNKNOWN #$code"
    }
}
