name: Create Release
on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    # check that we create a release over a commit with a tag
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: lib-bhttp/build/libs/lib-bhttp.jar
          token: ${{ secrets.GITHUB_TOKEN }}
